[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
    execute 'source' expand(g:plugin_settings . 'deoplete.vimrc')
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_add = '''
    execute 'source' expand(g:plugin_settings . 'deoplete-jedi.vimrc')
'''

[[plugins]]
repo = 'Shougo/neosnippet'
hook_add = '''
    execute 'source' expand(g:plugin_settings . 'neosnippet.vimrc')
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'davidhalter/jedi-vim'
#on_ft = 'python'
hook_add = '''
    execute 'source' expand(g:plugin_settings . 'jedi.vimrc')
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
depends = ['crtlp.vim']
